/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'
import { Route as PolicySlugRouteImport } from './routes/policy/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicySlugRoute = PolicySlugRouteImport.update({
  id: '/policy/$slug',
  path: '/policy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/category/$slug': typeof CategorySlugRoute
  '/policy/$slug': typeof PolicySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/category/$slug': typeof CategorySlugRoute
  '/policy/$slug': typeof PolicySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/category/$slug': typeof CategorySlugRoute
  '/policy/$slug': typeof PolicySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/favorites'
    | '/login'
    | '/category/$slug'
    | '/policy/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/favorites'
    | '/login'
    | '/category/$slug'
    | '/policy/$slug'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/favorites'
    | '/login'
    | '/category/$slug'
    | '/policy/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  CategorySlugRoute: typeof CategorySlugRoute
  PolicySlugRoute: typeof PolicySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/$slug': {
      id: '/policy/$slug'
      path: '/policy/$slug'
      fullPath: '/policy/$slug'
      preLoaderRoute: typeof PolicySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  CategorySlugRoute: CategorySlugRoute,
  PolicySlugRoute: PolicySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
